NAME=parser
CC=gcc
CFLAGS=-O2 -std=c99 -Wall  -pedantic -g -rdynamic -fms-extensions

$(NAME): $(NAME).c
			$(CC) $(CFLAGS) $(NAME).c -o ifj16
all: 
	$(CC) $(CFLAGS) $(NAME) -o NAME
clean :
	 	rm -f *.o *.core parser
